const express = require('express');
const crypto = require('crypto');// this is a built in node module that allows us to generate random strings
const z = require('zod'); // this is a schema validation library - mtaches correct data formtas (int , char etc)
const cors = require('cors'); // this is a middleware that allows us to enable CORS (Cross-Origin Resource Sharing) for our API. This is useful for allowing our API to be accessed from different domains.

const app = express();
app.use(cors());
app.use(express.json());

// 1. Data Store (in-memory mock databse)

const db = new Map(); // this is a built in data structure that allows us to store key value pairs
const generateShortCode = (length = 6) => {
    return crypto.randomBytes(length).toString("base64url").slice(0, length); // this generates a random string of 6 characters that we will use as the short code for our URL  
} // this generates a random string of 6 characters that we will use as the short code for our URL
// Zod - validation Schema
// toString converts the random bytes to a base64url string, which is a URL-safe version of base64 encoding. The slice method is used to limit the length of the string to the specified length (6 characters in this case).
const createUrlSchema = z.object({
    body: z.object({
        originalUrl : z.string({required_error: "URL IS NEEDED!"}).url("Must be a valid URL! (e.g https://example.com)"), 
    }),
});// this is a schema that defines the shape of the data we expect to receive in the request body. It expects an object with a single property orginalUrl which is a string and must be a valid URL. If the orginalUrl is not provided or is not a valid URL, it will return an error message.
// 3. Lets build the middleware zod

const  validate = (schema) =>(req, res, next) => {
    const result = schema.safeParse({
        body: req.body,
        query:req.query,
        params:req.params,
    })
    if (!result.success) {
        return res.status(400).json({ // status code 400 means bad req
            error: result.error.flatten().fieldErrors // what flatten does is it takes the error object and flattens it into a single object with the keys being the path to the error and the values being the error message. This makes it easier to read and understand the error messages.
        });
    }
    req.body = result.data.body;
    next();
};

// Lets now build route Handlers/ Controllers
 app.post('/api/shorten', validate(createUrlSchema), (req,res)=>{
    const {originalUrl} = req.body;
    const shortCode = generateShortCode(6);

    const record ={
        id: shortCode,
        originalUrl,
        clicks: 0,
        createdAt: new Date().toISOString(), // this is a built in method that returns the current date and time in ISO format e.g 2021-07-21T17:32:28.000Z
    };
    db.set(shortCode, record);

    const baseUrl = `${req.protocol}://${req.get("host")}`;  // this is a built in method that returns the protocol (http or https) and the host (domain name) of the request. This is useful for generating the full URL for the shortened link.

    return res.status(201).json({
        status: "success",
        data: {
            shortCode,
            shortUrl : `${baseUrl}/${shortCode}`,// this is the full URL for the shortened link. It is generated by concatenating the base URL with the short code. For example, if the base URL is http://localhost:3000 and the short code is abc123, the short URL will be http://localhost:3000/abc123
            originalUrl,
        },
    });    
 });


 // view click count & other infos

 app.get('/api/stats/:code', (req,res)=>{
    const {code } = req.params;
    const record = db.get(code);

    if(!record){
        return res.status(404).json({error : "Short URL not found!"});
    }
    return res.status(200).json({
        status: "success",
        data: record,
    });
 });    

 // Now lets redirect to original url;
 app.get('/:code', (req,res)=>{
    const {code} = req.params;
    const record = db.get(code);

    if(!record){
        return res.status(404).json({error : "Short URL not found!"});
    }
    record.clicks++;
    return res.redirect(302, record.originalUrl); // 302 is a status code that means "Found" and it tells the browser to redirect to the original URL. The original URL is stored in the record object that we retrieved from the database using the short code.
 }); 

 // lets build the server listener

 app.listen(3000, ()=>{
    console.log("Server is running on port 3000");
 });